// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMLehnsVLbjjo0TyKnIGLzpJuDEsxW-9A',
    appId: '1:943547303388:web:2f47aaaa109a97376c3b19',
    messagingSenderId: '943547303388',
    projectId: 'evstation-7caf2',
    authDomain: 'evstation-7caf2.firebaseapp.com',
    databaseURL: 'https://evstation-7caf2-default-rtdb.firebaseio.com',
    storageBucket: 'evstation-7caf2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFS-i-ugJkiOwJ5kaHXVcod0zQc_Zr7ks',
    appId: '1:943547303388:android:fee20a0c3c4d36196c3b19',
    messagingSenderId: '943547303388',
    projectId: 'evstation-7caf2',
    databaseURL: 'https://evstation-7caf2-default-rtdb.firebaseio.com',
    storageBucket: 'evstation-7caf2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7xo01AWUJGHUyZcExh4HDKli5Qex5yvg',
    appId: '1:943547303388:ios:ce250badd9e833146c3b19',
    messagingSenderId: '943547303388',
    projectId: 'evstation-7caf2',
    databaseURL: 'https://evstation-7caf2-default-rtdb.firebaseio.com',
    storageBucket: 'evstation-7caf2.firebasestorage.app',
    iosBundleId: 'com.example.openStreetMapExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7xo01AWUJGHUyZcExh4HDKli5Qex5yvg',
    appId: '1:943547303388:ios:ce250badd9e833146c3b19',
    messagingSenderId: '943547303388',
    projectId: 'evstation-7caf2',
    databaseURL: 'https://evstation-7caf2-default-rtdb.firebaseio.com',
    storageBucket: 'evstation-7caf2.firebasestorage.app',
    iosBundleId: 'com.example.openStreetMapExample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMLehnsVLbjjo0TyKnIGLzpJuDEsxW-9A',
    appId: '1:943547303388:web:652d079da224fad96c3b19',
    messagingSenderId: '943547303388',
    projectId: 'evstation-7caf2',
    authDomain: 'evstation-7caf2.firebaseapp.com',
    databaseURL: 'https://evstation-7caf2-default-rtdb.firebaseio.com',
    storageBucket: 'evstation-7caf2.firebasestorage.app',
  );

}